### ISSUE TITLE
I have a problem when I upgrade next to v9

### ISSUE THREAD

**Issue by phakphumi** [sdli/next-antd-aza-less#5]
When I try to run `next build` on the docker container below error appear.

`
> Build error occurred
{ /usr/src/app/node_modules/antd/lib/style/index.less:1
@import './themes/default';
^
`
`
SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/src/app/node_modules/antd/lib/button/style/index.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10) type: 'SyntaxError', '$error': '$error' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

By the way, this error doesn't appear when I run next start.

Note: I have set up the project according to the document

**Comment by phakphumi** [comment]
Also, I have tried to change .babelrc configuration from `"import", { "libraryName": "antd", "style": true}` to `"import", { "libraryName": "antd", "style": "css"}` that cause me face another error.
`
Failed to compile.

./node_modules/antd/lib/checkbox/style/index.css 5:0
Module parse failed: Unexpected character '@' (5:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| /* stylelint-disable */
| /* stylelint-disable declaration-bang-space-before,no-duplicate-selectors,string-no-newline */
> @-webkit-keyframes antCheckboxEffect {
|   0% {
|     -webkit-transform: scale(1);

> Build error occurred
Error: > Build failed because of webpack errors
    at build (/Users/pakpoom/Documents/boilerplate-frontend-ssr/node_modules/next/dist/build/index.js:6:363)
error Command failed with exit code 1.
`

**Comment by phakphumi** [comment]
Also, I have tried to change .babelrc configuration from `"import", { "libraryName": "antd", "style": true}` to `"import", { "libraryName": "antd", "style": "css"}` that cause me face another error.

`Failed to compile.`

`./node_modules/antd/lib/checkbox/style/index.css 5:0
Module parse failed: Unexpected character '@' (5:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
`
`
| /* stylelint-disable */
| /* stylelint-disable declaration-bang-space-before,no-duplicate-selectors,string-no-newline */
\> @-webkit-keyframes antCheckboxEffect {
|   0% {
|     -webkit-transform: scale(1);
`

`
\> Build error occurred
Error: > Build failed because of webpack errors
    at build (/Users/#/Documents/#/node_modules/next/dist/build/index.js:6:363)
error Command failed with exit code 1.
`

**Comment by baojiawei** [comment]
May I ask whether this issue has been settled? I had the same problem and needed help

**Comment by cundejo** [comment]
Any news guys? 
I'm having the same issue on Next.js 10, when running `next dev` everything is fine; but running `next build` raises this error, even deploying on Vercel.
