### ISSUE TITLE
按照你的配置步骤配置后，项目可以跑起来，但是打包出

### ISSUE THREAD

**Issue by 530212558** [sdli/next-antd-aza-less#9]
> Build error occurred
{ D:\（WEB）\react\proscenic-next\node_modules\antd\lib\style\index.less:1
(function (exports, require, module, __filename, __dirname) { @import './themes/index';
                                                              ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18) type: 'SyntaxError' }
Creating an optimized production build .Automatically optimizing pages .npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! proscenic-next@0.1.0 build: `next build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the proscenic-next@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by lbjlsy** [comment]
兄弟解决了吗？

**Comment by 530212558** [comment]
没有解决，弃坑了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sdli/next-antd-aza-less"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月12日(星期天) 中午11:28
收件人:&nbsp;"sdli/next-antd-aza-less"<next-antd-aza-less@noreply.github.com&gt;;
抄送:&nbsp;"♂"<530212558@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [sdli/next-antd-aza-less] 按照你的配置步骤配置后，项目可以跑起来，但是打包出 (#9)





 
兄弟解决了吗？
